In [4]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim


In [5]:
#One sample with two features
X = torch.tensor([[2.0,3.0]])

In [14]:
#create model of 3 neurons with 2 inputs ( so each neuron sees same 2 inputs )

model_linear = nn.Linear(2,3)
relu = nn.ReLU()
print("weights:",model_linear.weight)
print("bias:",model_linear.bias)

output = model_linear(X)
output_relu = relu(output)

print("Before activation:", output)
print("After activation:", output_relu)

weights: Parameter containing:
tensor([[-0.4986,  0.6488],
        [-0.5373,  0.0385],
        [-0.1765, -0.3799]], requires_grad=True)
bias: Parameter containing:
tensor([-0.6529,  0.4028, -0.2569], requires_grad=True)
Before activation: tensor([[ 0.2962, -0.5562, -1.7495]], grad_fn=<AddmmBackward0>)
After activation: tensor([[0.2962, 0.0000, 0.0000]], grad_fn=<ReluBackward0>)


In [23]:
# A BASIC MULTILEVEL NN 
import torch
import torch.nn as nn

torch.manual_seed(42)
X = torch.tensor([[2.0,3.0]])

class NeuralNetwork(nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(2, 3)    # 2 inputs   3 neurons (outputs)
        self.layer2 = nn.Linear(3, 2)    # 3 inputs   2 neurons (outputs)
        self.layer3 = nn.Linear(2, 1)    # 2 inputs   1 neuron
        self.relu = nn.ReLU()

    def forward(self, x):

        x = self.relu(self.layer1(x))
        x = self.relu(self.layer2(x))
        x = self.layer3(x)

        return x
        
model = NeuralNetwork()

print("The predicted outcome is :",model.forward(X))


The predicted outcome is : tensor([[-0.4390]], grad_fn=<AddmmBackward0>)


In [33]:
# OPTIMIZING THE WEIGHTS OF A MULTILEVEL NN

torch.manual_seed(42)
X = torch.tensor([
    [2.0, 3.0],
    [1.0, 4.0],
    [3.0, 1.0]
])

y = torch.tensor([[5.0],[6.0],[4.0]])

class NeuralNetwork(nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(2, 3)    # 2 inputs   3 neurons (outputs)
        self.layer2 = nn.Linear(3, 2)    # 3 inputs   2 neurons (outputs)
        self.layer3 = nn.Linear(2, 1)    # 2 inputs   1 neuron
        self.relu = nn.ReLU()

    def forward(self, x):

        x = self.relu(self.layer1(x))
        x = self.relu(self.layer2(x))
        x = self.layer3(x)

        return x


model = NeuralNetwork()
loss_fun = nn.MSELoss()
print("type of model ",type(model))
print("type of loss_fun ",type(loss_fun))
#INITIALIZE AN OPTIMIZER

optimizer = optim.SGD(model.parameters(),lr=0.01)

#Now start the optimization

for epoch in range(100):

    #FORWARD PROPAGATION
    prediction = model(X)

    #COMPUTE THE LOSS
    loss  = loss_fun(prediction,y)
    optimizer.zero_grad()

    #BACKPROPAGATION
    loss.backward()

    #UPDATE THE WEIGHTS AND BIAS
    optimizer.step()

 
print("\nOptimized parameters:")

'''for name, param in model.named_parameters():
    print(name)
    print(param.data)'''

print("FINAL WEIGHTS: ",model.layer3.weight.data)
print("FINAL BIAS: ",model.layer3.bias.data)

type of model  <class '__main__.NeuralNetwork'>
type of loss_fun  <class 'torch.nn.modules.loss.MSELoss'>

Optimized parameters:
layer1.weight
tensor([[0.6137, 0.5115],
        [0.1495, 0.8798],
        [0.0062, 0.2298]])
layer1.bias
tensor([-0.3317,  0.5505,  0.6880])
layer2.weight
tensor([[-0.1182,  0.8284,  0.2300],
        [ 0.6007,  0.2599,  0.3558]])
layer2.bias
tensor([0.0831, 0.5621])
layer3.weight
tensor([[0.5693, 0.7715]])
layer3.bias
tensor([0.9349])
FINAL WEIGHTS:  tensor([[0.5693, 0.7715]])
FINAL BIAS:  tensor([0.9349])
